### ISSUE TITLE
Some conversions are missing from edm4hep to lcio?

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/k4EDM4hep2LcioConv#93] opened 2024-09-04 15:10 UTC
`VertexRecoParticleLink, ClusterMCParticleLink, RecoMCParticleLink` if I didn't miss any (mostly surprised about the last one)

example file: https://cernbox.cern.ch/s/KBOJk8qBowfyaSn

"full" output:

```
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name BCalRecoParticle_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name BuildUpVertex_RP_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name BuildUpVertex_V0_RP_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name BuildUpVertex_V0_associatedParticles
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name BuildUpVertex_associatedParticles
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::ClusterMCParticleLink with name ClusterMCTruthLink
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name FinalColourNeutrals_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::RecoMCParticleLink with name FinalElementonLink
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name GammaGammaCandidateEtaPrimes_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name GammaGammaCandidateEtas_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name GammaGammaCandidatePi0s_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name InitialColourNeutrals_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::RecoMCParticleLink with name InitialElementonLink
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name KinkRecoParticles_startVertices
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
ToolSvc.InputCo...WARNING Error trying to convert requested edm4hep::VertexRecoParticleLink with name KinkVertices_associatedParticles
ToolSvc.InputCo...WARNING List of supported types: Track, TrackerHit3D, TrackerHitPlane, SimTrackerHit, Cluster, CalorimeterHit, RawCalorimeterHit, SimCalorimeterHit, Vertex, ReconstructedParticle, MCParticle.
```

**Comment by tmadlener** [comment] 2024-09-04 15:17
I think this is a duplicate of https://github.com/key4hep/k4MarlinWrapper/issues/199

**Comment by Zehvogel** [comment] 2024-09-04 15:24
Urgh, possibly, although now I am even more confused how we reach this printout...

**Comment by Zehvogel** [comment] 2024-09-04 15:25
Nvm., its here:

https://github.com/key4hep/k4MarlinWrapper/blob/b6c0ec6b74990fd40db276e923d54e06cee5fb54/k4MarlinWrapper/src/components/EDM4hep2Lcio.cpp#L352-L359

**Closed** 2024-09-09 08:14 UTC
